### PR TITLE
Add @usedapp/uniswap  which provides useUniswapPrice hook

### PR DESCRIPTION
**Pull request by shota-masuda-onibakuchi**
Uniswap is not only a simple exchange for tokens, but also has the function of PriceOracle. This PR introduces `@usedapp/uniswap` and a hook `useUniswapPrice(baseCurrency : string ,quateCurrency: string , overrides?:{factory:address,digits:number}) => FixedNumber | undefined` 

This hook will return a peek price from the Uniswap V2 pool, calculated from the address of the given token. If there is no direct path or unconnected, it returns `undefined`. This hooks doesn't depend on Uniswap SDK. I think that in most cases, we just want to know the price, so we don't need to think about complicated paths.
uniswap determines the price from the pool reserve (e.g ETH/DAI, ETH-DAI price =  the reserve of Dai / the reserve of WETH)
By overriding `factory`  address, this hook can use sushiswap as a price feed.
I'm not a native English speaker, so maybe there are some problems in my words

### CODE REVIEW

**Comment by noobshow** [comment]
I guess the hooks provided are more than that you specified, will addLiquidity() be required to get token's price?

**Comment by shota-masuda-onibakuchi** [comment]
> I guess the hooks provided are more than that you specified, will addLiquidity() be required to get token's price?

I eventually removed the hooks in the commit message except for `useUniswapPrice`.

To get the price of the token, addLiquidity() is not needed. UniswapV2 doesn't have a function to return the price, we need to calculate token's price. So, the `useUniswapPrice` hook call `getReserves` function of UniswapV2Pair.
`function getReserves() public view returns(uint112 reserve0 ,uint112 reserve1, uint112 timestamp)`, 
And then, the ratio of reserves is token's price.

**Comment by marekkirejczyk** [comment]
Hi @shota-masuda-onibakuchi,

Great work so far ❤️ 
It is a bit difficult to read, because of many formatting changes. And the linter is failing. 
Would you fix it? 

Marek

**Comment by noobshow** [comment]
Hi @shota-masuda-onibakuchi,
If i could make a suggestion, to avoid issues with many other lines you've changed on your local branches conflicting with other merged codes(formatting, linting, etc), for example, i saw many files changed with just the "," comma removed, perhaps its the work of your beautifier which doesn't seem to be the way prettier/prettier(existing dependency for formatting on the project) does format codes...

My suggestion would be to dump this branch as there's been too much changes to review, even for @marekkirejczyk in a short time and reviewing for security reason is important too, dump the branch and extract the specific changes you are proposing to a new branch without it affecting tests, linting and formatting of other files...

Just a suggestion, to make the review process faster, safer and secure for everyone involved...

You did something i really need to implement.

Nice work 👍

**Comment by shota-masuda-onibakuchi** [comment]
Hi, @noobshow @marekkirejczyk 
You are right . I apologize for not knowing the basics as I do not have  much experience in collaboration. 🙇 

> My suggestion would be to dump this branch 

How do I do a ''dump''?.

>   dump the branch and extract the specific changes you are proposing to a new branch without it affecting tests, linting and formatting of other files...

I understand that I can extract specific changes to another branch. I may not be understanding correctly, does it mean creating a new pull request?

**Comment by noobshow** [comment]
Creating a new PR might suffice, after you've extracted the changes to the new branch, so it won't affect linting and formatting for you and everyone... 

At this current stage, fixing the formatting might even be tedious for you... 

We all started learning once before 😉
Nice work, once again...

**Comment by Szymx95** [comment]
Running  `yarn lint:fix` should be enough to fix formatting

**Comment by noobshow** [comment]
> Running `yarn lint:fix` should be enough to fix formatting

The reason I asked him to make a new branch is to clear git of the changes history done to the other various files, I think lint fix might restore the changes too, hopefully restore the history as if nothing happened to them also...

**Comment by Szymx95** [comment]
When we merge we do squash&merge and then delete the branch. Therefore only the final changes to files are stored

**Comment by shota-masuda-onibakuchi** [comment]
I just maked a new branch and a new PR.
 - linting and formatting pass
- extract specific changes

**Comment by marekkirejczyk** [comment]
Closing, continued in #257

**Pull request closed without merging**
