### PR TITLE
Adding Cronos network support.

### PR DESCRIPTION
**Pull request by CasperGhostCrypto**

### CODE REVIEW

**Comment by CasperGhostCrypto** [comment]
@gasolin I have made the modification as per previous PR

**Comment by CasperGhostCrypto** [comment]
@tt-marek review please?

**Review by tt-marek — APPROVED** [review]

**Comment by tt-marek** [comment]
LGTM ❤️ Need to fix lint

**Comment by CasperGhostCrypto** [comment]
Fixed, but looks like deploy is still failing.. `yarn lint` and `yarn test` pass locally on my machine.

**Comment by CasperGhostCrypto** [comment]
Ok this time it should work.. promise. Any timeframe on when the next npm publish occurs? I can't seem to link this package locally to finish developing my app :(

**Pull request merged**
