### PR TITLE
🧿 update node matrix in CI

### PR DESCRIPTION
**Pull request by marcin-trust**
Align with current LTS support

12, 14, 16 are LTS versions
https://nodejs.org/en/about/releases/

### CODE REVIEW

**Comment by jodator** [comment]
@marcin-trust It looks like the `test 16` was canceled. I'm re-running the jobs to see if this was a GH hickup.

**Comment by marcin-trust** [comment]
@jodator at the same time you need to reconfigure branch policy and remove 10.x and 12.x required checks

**Comment by jodator** [comment]
> @jodator at the same time you need to reconfigure branch policy and remove 10.x and 12.x required checks

Yep, we will need to do this after the merge. For now, it looks like the job on node `16` is running for too long. Could check why is that?

**Comment by marcin-trust** [comment]
node v16 test run hangs locally. why-is-node-running prints forever in async hook loop or sth.
I added `--exit` to mocha and I'll create an issue

**Comment by marcin-trust** [comment]
#476 related

**Comment by marcin-trust** [comment]
> I added --exit to mocha and I'll create an issue

It didn't help

**Comment by jodator** [comment]
> It didn't help

@marcin-trust Could you check to add `--exit` flag to other packages? I've tested this locally, and I had to add this flag to all packages.

**Comment by marcin-trust** [comment]
@jodator - yes, it helped, let's see in this PR

**Comment by marcin-trust** [comment]
I forgot about testing project. Now it should work in CI too

**Comment by marcin-trust** [comment]
It got passed. Now you @jodator need to update the required check rules.

**Comment by jodator** [comment]
@marcin-trust I think that the last step is also to include a change set as we introduce a breaking change. Since we're still on `0.x` I'd go with MINOR. Other than that, we're good to go.

**Review by jodator — APPROVED** [review]

**Pull request merged**
