### PR TITLE
✨ add gnosis chain as xdai alias

### PR DESCRIPTION
**Pull request by gasolin**
refer https://www.xdaichain.com/

xdai chain has rename to gnosis chain

Due to lots of user use the legacy xdai name, tend to keep it and just add the alias

### CODE REVIEW

**Comment by tt-marek** [comment]
This is compatibility breaking change, can we have both names?

**Comment by gasolin** [comment]
added back

**Comment by tt-marek** [comment]
Needs. rebase + conflict solving

**Comment by gasolin** [comment]
rebased

**Review by tt-marek — APPROVED** [review]

**Pull request merged**
