### PR TITLE
Add support for Theta

### PR DESCRIPTION
**Pull request by jieyilong**

### CODE REVIEW

**Review by marekkirejczyk — APPROVED** [review]

**Comment by marekkirejczyk** [comment]
Hi @jieyilong,
Sorry for slow reaction 🐢 
Great job ❤️ 
Happy to merge it, would you solve conflicts?

**Comment by jieyilong** [comment]
> Hi @jieyilong, Sorry for slow reaction 🐢 Great job ❤️ Happy to merge it, would you solve conflicts?

No problem, thanks for the heads-up! I've just resolved the conflict and merged the changes. Please let me know if any change is needed. Thanks!

**Comment by marekkirejczyk** [comment]
Would you also add a changeset -> you need to click on "Click here if you're a maintainer who wants to add a changeset to this PR" in a comment from changeset bot. It si required for proper versioning.

**Comment by jieyilong** [comment]
> Would you also add a changeset -> you need to click on "Click here if you're a maintainer who wants to add a changeset to this PR" in a comment from changeset bot. It si required for proper versioning.

Sure, just did :)

**Review by marekkirejczyk — APPROVED** [review]

**Comment by marekkirejczyk** [comment]
Published

**Comment by jieyilong** [comment]
> Published

Awesome, thanks @marekkirejczyk !

**Pull request merged**
