### PR TITLE
🤙 Return error from useContractCall

### PR DESCRIPTION
**Pull request by HubertNastaly**
In current useContractCall implementation we get `undefined` in both cases: when data is not fetched yet or when an error occurs. This PR will provide the functionality to distinguish these cases.

### CODE REVIEW

**Comment by nezouse** [comment]
Did you test if messages are anyhow meaningful? Probably on ganache they will be different, but would be good to check that.

**Review by marekkirejczyk — CHANGES_REQUESTED** [review]
As discussed - introduce new function `useCall` to avoid compatibility breaking changes

**Comment by nezouse** [comment]
If introduced as new call in same PR please change the changeset as i marked it as minor, because it was breaking change.

**Review by Tono1852 — CHANGES_REQUESTED** [review]
@

**Pull request closed without merging**
